version: "3.8"

services:
  backend:
    container_name: meetscribe-backend
    build:
      context: ./meetscribe-backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: meetscribe-postgres
    restart: always
    environment:
      POSTGRES_DB: meetscribe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
