server:
  port: 8080

spring:
  application:
    name: meetscribe-gateway

  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - AddResponseHeader=X-Gateway, MeetScribe

      routes:
        - id: backend-service
          uri: http://meetscribe-backend:8081
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}

  data:
    redis:
      host: redis
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info