server:
  port: 8081
  forward-headers-strategy: framework

spring:
  jackson:
    time-zone: UTC
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

security:
  jwt:
    secret: ${JWT_SECRET}
    expiry: 3600000


# 🔑 REQUIRED FOR DOCKER HEALTHCHECK
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true