name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Gateway
        run: |
          echo "Calling gateway..."
          curl -s -o /dev/null -w "Gateway Status: %{http_code}\n" https://meetscribe-gateway.onrender.com/actuator/health

      - name: Ping Backend
        run: |
          echo "Calling backend..."
          curl -s -o /dev/null -w "Backend Status: %{http_code}\n" https://meetscribe-server.onrender.com/actuator/health
